skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract = "B1BL9SDgz2XDkv7yHQYwJoRE5y6sskVgGQZWBzo5W9Ko"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
